//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpadCompanyPanel.Web.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SpadCompanyPanel.Web.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abu Dhabi.
        /// </summary>
        public static string AbuDhabi {
            get {
                return ResourceManager.GetString("AbuDhabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afghanistan.
        /// </summary>
        public static string Afghanistan {
            get {
                return ResourceManager.GetString("Afghanistan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alanya.
        /// </summary>
        public static string Alanya {
            get {
                return ResourceManager.GetString("Alanya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All About Estate and investments.
        /// </summary>
        public static string Allaboutthelatestamazingupdates {
            get {
                return ResourceManager.GetString("Allaboutthelatestamazingupdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ankara.
        /// </summary>
        public static string Ankara {
            get {
                return ResourceManager.GetString("Ankara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antalya.
        /// </summary>
        public static string Antalya {
            get {
                return ResourceManager.GetString("Antalya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apartment.
        /// </summary>
        public static string Apartment {
            get {
                return ResourceManager.GetString("Apartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area.
        /// </summary>
        public static string Area {
            get {
                return ResourceManager.GetString("Area", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Area guide.
        /// </summary>
        public static string Areaguide {
            get {
                return ResourceManager.GetString("Areaguide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Armenia.
        /// </summary>
        public static string Armenia {
            get {
                return ResourceManager.GetString("Armenia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Articles {
            get {
                return ResourceManager.GetString("Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bathroom.
        /// </summary>
        public static string Bathroom {
            get {
                return ResourceManager.GetString("Bathroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedroom.
        /// </summary>
        public static string Bedroom {
            get {
                return ResourceManager.GetString("Bedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Suggestion.
        /// </summary>
        public static string BestSuggestion {
            get {
                return ResourceManager.GetString("BestSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blog Detail.
        /// </summary>
        public static string BlogDetail {
            get {
                return ResourceManager.GetString("BlogDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cities.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercial.
        /// </summary>
        public static string Commercial {
            get {
                return ResourceManager.GetString("Commercial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consultants.
        /// </summary>
        public static string Consultants {
            get {
                return ResourceManager.GetString("Consultants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phones.
        /// </summary>
        public static string ContactPhones {
            get {
                return ResourceManager.GetString("ContactPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Us.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Easiest way for buy a house.
        /// </summary>
        public static string ContactUsAbout {
            get {
                return ResourceManager.GetString("ContactUsAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designed by .
        /// </summary>
        public static string Designedby {
            get {
                return ResourceManager.GetString("Designedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubai.
        /// </summary>
        public static string Dubai {
            get {
                return ResourceManager.GetString("Dubai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplex.
        /// </summary>
        public static string Duplex {
            get {
                return ResourceManager.GetString("Duplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Land.
        /// </summary>
        public static string Earth {
            get {
                return ResourceManager.GetString("Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email address is already exists.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is not valid.
        /// </summary>
        public static string EmailNotValidError {
            get {
                return ResourceManager.GetString("EmailNotValidError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Email Address.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write Your Message.
        /// </summary>
        public static string EnterContext {
            get {
                return ResourceManager.GetString("EnterContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter your email.
        /// </summary>
        public static string EnterEmailError {
            get {
                return ResourceManager.GetString("EnterEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email.
        /// </summary>
        public static string Enteryouremail {
            get {
                return ResourceManager.GetString("Enteryouremail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estate Guide.
        /// </summary>
        public static string EstateGuide {
            get {
                return ResourceManager.GetString("EstateGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estates.
        /// </summary>
        public static string Estates {
            get {
                return ResourceManager.GetString("Estates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estate Search.
        /// </summary>
        public static string EstateSearch {
            get {
                return ResourceManager.GetString("EstateSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experts Suggestion.
        /// </summary>
        public static string ExpertsSuggestion {
            get {
                return ResourceManager.GetString("ExpertsSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your dream home in your city.
        /// </summary>
        public static string Findyourdreamhomeinyourcity {
            get {
                return ResourceManager.GetString("Findyourdreamhomeinyourcity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find your Villa now.
        /// </summary>
        public static string Findyourhomeinyourcitynow {
            get {
                return ResourceManager.GetString("Findyourhomeinyourcitynow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your first name.
        /// </summary>
        public static string FirstNameRequired {
            get {
                return ResourceManager.GetString("FirstNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Five Bedrooms.
        /// </summary>
        public static string FiveBedrooms {
            get {
                return ResourceManager.GetString("FiveBedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floor.
        /// </summary>
        public static string Floor {
            get {
                return ResourceManager.GetString("Floor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow Us.
        /// </summary>
        public static string FollowUs {
            get {
                return ResourceManager.GetString("FollowUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For sale.
        /// </summary>
        public static string Forsale {
            get {
                return ResourceManager.GetString("Forsale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Bedrooms.
        /// </summary>
        public static string FourBedrooms {
            get {
                return ResourceManager.GetString("FourBedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        public static string Gallery {
            get {
                return ResourceManager.GetString("Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instagram.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introducing real estate with the possibility of buying with the currency code.
        /// </summary>
        public static string Introducingwiththecurrencycode {
            get {
                return ResourceManager.GetString("Introducingwiththecurrencycode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Investment Guide.
        /// </summary>
        public static string InvestmentGuide {
            get {
                return ResourceManager.GetString("InvestmentGuide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iran.
        /// </summary>
        public static string Iran {
            get {
                return ResourceManager.GetString("Iran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isfahan.
        /// </summary>
        public static string Isfahan {
            get {
                return ResourceManager.GetString("Isfahan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Istanbul.
        /// </summary>
        public static string Istanbul {
            get {
                return ResourceManager.GetString("Istanbul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konya.
        /// </summary>
        public static string Konya {
            get {
                return ResourceManager.GetString("Konya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your last name.
        /// </summary>
        public static string LastNameRequired {
            get {
                return ResourceManager.GetString("LastNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest News.
        /// </summary>
        public static string LatestNews {
            get {
                return ResourceManager.GetString("LatestNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Let us call you, we will help you to choose the best investment.
        /// </summary>
        public static string LetUsCallYou {
            get {
                return ResourceManager.GetString("LetUsCallYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Luxurious villa.
        /// </summary>
        public static string LuxVilla {
            get {
                return ResourceManager.GetString("LuxVilla", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Real State For.
        /// </summary>
        public static string MalikFor {
            get {
                return ResourceManager.GetString("MalikFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mashhad.
        /// </summary>
        public static string Mashhad {
            get {
                return ResourceManager.GetString("Mashhad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modern Houses.
        /// </summary>
        public static string ModernHouses {
            get {
                return ResourceManager.GetString("ModernHouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Properties.
        /// </summary>
        public static string NewProperties {
            get {
                return ResourceManager.GetString("NewProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string News {
            get {
                return ResourceManager.GetString("News", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News and Articles.
        /// </summary>
        public static string NewsandArticles {
            get {
                return ResourceManager.GetString("NewsandArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Detail.
        /// </summary>
        public static string NewsDetail {
            get {
                return ResourceManager.GetString("NewsDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بعدي.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasional real estate at a reasonable price.
        /// </summary>
        public static string OccasionalRealEstateAtaReasonablePrice {
            get {
                return ResourceManager.GetString("OccasionalRealEstateAtaReasonablePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official.
        /// </summary>
        public static string Official {
            get {
                return ResourceManager.GetString("Official", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Bedroom.
        /// </summary>
        public static string OneBedroom {
            get {
                return ResourceManager.GetString("OneBedroom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Option {
            get {
                return ResourceManager.GetString("Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to our colleagues.
        /// </summary>
        public static string ourcolleagues {
            get {
                return ResourceManager.GetString("ourcolleagues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our colleagues are available 24 hours a day.
        /// </summary>
        public static string Ourcolleaguesareavailable24hoursaday {
            get {
                return ResourceManager.GetString("Ourcolleaguesareavailable24hoursaday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parking.
        /// </summary>
        public static string Parking {
            get {
                return ResourceManager.GetString("Parking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password is less than six characters.
        /// </summary>
        public static string PasswordIsLessthanSix {
            get {
                return ResourceManager.GetString("PasswordIsLessthanSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password must include a Captal letter, a lower case letter and a symbol.
        /// </summary>
        public static string PasswordIsNotStrong {
            get {
                return ResourceManager.GetString("PasswordIsNotStrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your password.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Phone number is already exists.
        /// </summary>
        public static string PhoneNumberExists {
            get {
                return ResourceManager.GetString("PhoneNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Not Exist.
        /// </summary>
        public static string PhoneNumberNotExist {
            get {
                return ResourceManager.GetString("PhoneNumberNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Phone Number.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan.
        /// </summary>
        public static string Plan {
            get {
                return ResourceManager.GetString("Plan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan Sample.
        /// </summary>
        public static string PlanSample {
            get {
                return ResourceManager.GetString("PlanSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre Sale.
        /// </summary>
        public static string PreSale {
            get {
                return ResourceManager.GetString("PreSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Filter.
        /// </summary>
        public static string PriceFilter {
            get {
                return ResourceManager.GetString("PriceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estate Type.
        /// </summary>
        public static string PropertyType {
            get {
                return ResourceManager.GetString("PropertyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Articles.
        /// </summary>
        public static string RecentArticles {
            get {
                return ResourceManager.GetString("RecentArticles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Estates.
        /// </summary>
        public static string RecentStates {
            get {
                return ResourceManager.GetString("RecentStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rent.
        /// </summary>
        public static string Rent {
            get {
                return ResourceManager.GetString("Rent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Europe.
        /// </summary>
        public static string ResidenceinEurope {
            get {
                return ResourceManager.GetString("ResidenceinEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAE.
        /// </summary>
        public static string ResidenceintheUAE {
            get {
                return ResourceManager.GetString("ResidenceintheUAE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        public static string ResidenceinTurkey {
            get {
                return ResourceManager.GetString("ResidenceinTurkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype password.
        /// </summary>
        public static string ReTypePassword {
            get {
                return ResourceManager.GetString("ReTypePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retype password is not correct.
        /// </summary>
        public static string ReTypePasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("ReTypePasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter retype of password.
        /// </summary>
        public static string ReTypePasswordRequired {
            get {
                return ResourceManager.GetString("ReTypePasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rules.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russia.
        /// </summary>
        public static string Russia {
            get {
                return ResourceManager.GetString("Russia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Feature.
        /// </summary>
        public static string SearchFeature {
            get {
                return ResourceManager.GetString("SearchFeature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Message To Us.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shiraz.
        /// </summary>
        public static string Shiraz {
            get {
                return ResourceManager.GetString("Shiraz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorted by.
        /// </summary>
        public static string Sortedby {
            get {
                return ResourceManager.GetString("Sortedby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spad.
        /// </summary>
        public static string Spad {
            get {
                return ResourceManager.GetString("Spad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special investment Estate.
        /// </summary>
        public static string SpecialInvestmentProperty {
            get {
                return ResourceManager.GetString("SpecialInvestmentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string State {
            get {
                return ResourceManager.GetString("State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stay in Europe.
        /// </summary>
        public static string StayinEurope {
            get {
                return ResourceManager.GetString("StayinEurope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to Newsletter.
        /// </summary>
        public static string SubscribetoNewsletter {
            get {
                return ResourceManager.GetString("SubscribetoNewsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tags.
        /// </summary>
        public static string Tags {
            get {
                return ResourceManager.GetString("Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tehran.
        /// </summary>
        public static string Tehran {
            get {
                return ResourceManager.GetString("Tehran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Contact Ways.
        /// </summary>
        public static string TheWayForContact {
            get {
                return ResourceManager.GetString("TheWayForContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Three Bedrooms.
        /// </summary>
        public static string ThreeBedrooms {
            get {
                return ResourceManager.GetString("ThreeBedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toman.
        /// </summary>
        public static string Toman {
            get {
                return ResourceManager.GetString("Toman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey.
        /// </summary>
        public static string Turkey {
            get {
                return ResourceManager.GetString("Turkey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turkey News.
        /// </summary>
        public static string TurkeyNews {
            get {
                return ResourceManager.GetString("TurkeyNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special real estate packages for Turkish citizenship and passports.
        /// </summary>
        public static string Turkishcitizenshipandpassports {
            get {
                return ResourceManager.GetString("Turkishcitizenshipandpassports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two Bedrooms.
        /// </summary>
        public static string TwoBedrooms {
            get {
                return ResourceManager.GetString("TwoBedrooms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Van.
        /// </summary>
        public static string Van {
            get {
                return ResourceManager.GetString("Van", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Villa.
        /// </summary>
        public static string Villa {
            get {
                return ResourceManager.GetString("Villa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual Tour.
        /// </summary>
        public static string Vt {
            get {
                return ResourceManager.GetString("Vt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ways to contactus.
        /// </summary>
        public static string Waystocontactus {
            get {
                return ResourceManager.GetString("Waystocontactus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WC.
        /// </summary>
        public static string WC {
            get {
                return ResourceManager.GetString("WC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are available 24 hours a day.
        /// </summary>
        public static string Weareavailable24hoursaday {
            get {
                return ResourceManager.GetString("Weareavailable24hoursaday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We give you the best.
        /// </summary>
        public static string WeGiveYouTheBest {
            get {
                return ResourceManager.GetString("WeGiveYouTheBest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Bright House.
        /// </summary>
        public static string WelcomeToBr {
            get {
                return ResourceManager.GetString("WelcomeToBr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to what do you want.
        /// </summary>
        public static string WhatDoYouWant {
            get {
                return ResourceManager.GetString("WhatDoYouWant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WhatsApp.
        /// </summary>
        public static string WhatsApp {
            get {
                return ResourceManager.GetString("WhatsApp", resourceCulture);
            }
        }
    }
}
