// <auto-generated />
namespace SpadCompanyPanel.Infrastructure.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class changedrealState : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedrealState));
        
        string IMigrationMetadata.Id
        {
            get { return "202101270929126_changed-realState"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
